MINI_PROGRAM_APPID = "appid"
MINI_PROGRAM_APPSECRET = "appsecret"
JWT_SECRET = "jwtsecret"
JWT_ALGORITHM = "HS512"
JWT_EXPIRE_SECONDS = 30 * 86400 # 1 month
URI_SCHEME = "http"
URI_AUTHORITY = "localhost:5000"